[tools]
aws = "latest"
cosign = "latest"
eza = "latest"
gallery-dl = "latest"
gh = "latest"
go = "latest"
golangci-lint = "latest"
kubectl = "latest"
mage = "latest"
slsa-verifier = "latest"
kubens = "latest"
kubectx = "latest"
yt-dlp = "latest"
jless = "latest"
node = "22"
julia = "latest"
