[tools]
cosign = "latest"
eza = "latest"
gallery-dl = "latest"
gh = "latest"
kubectl = "latest"
mage = "latest"
slsa-verifier = "latest"
kubens = "latest"
kubectx = "latest"
yt-dlp = "latest"
jless = "latest"
node = "22"
golangci-lint = "latest"
helm = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
television = "latest"
go = "latest"
